<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos[
<!ELEMENT pedidos (anno*)>
<!ELEMENT anno (trimestre*)>
<!ATTLIST anno year CDATA #REQUIRED>
<!ELEMENT trimestre (pedido+)>
<!ATTLIST trimestre num CDATA #REQUIRED>
<!ELEMENT pedido (cliente, fecha_inclusion, detalle_pedido)>
<!ELEMENT cliente (nombre, apellidos, telefono, direccion, correo_electronico)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle, ciudad, codigo_postal, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT correo_electronico (#PCDATA)>
<!ELEMENT fecha_inclusion (#PCDATA)>
<!ELEMENT detalle_pedido (numero_pedido, fecha_compra, fecha_entrega, total_factura, productos)>
<!ELEMENT numero_pedido (#PCDATA)>
<!ELEMENT fecha_compra (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total_factura (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre_producto, referencia, precio, unidades)>
<!ELEMENT nombre_producto (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

]>
<pedidos>
    <anno year="2021">
        <trimestre num="1">
            <pedido>
                <cliente>
                    <nombre>María</nombre>
                    <apellidos>González Pérez</apellidos>
                    <telefono>555-123-4567</telefono>
                    <direccion>
                        <calle>Calle Mayor, 1</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28001</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>maria.gonzalez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-01-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10001</numero_pedido>
                    <fecha_compra>2021-01-02</fecha_compra>
                    <fecha_entrega>2021-01-05</fecha_entrega>
                    <total_factura>29.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Camiseta de mujer</nombre_producto>
                            <referencia>ABC123</referencia>
                            <precio>29.99</precio>
                            <unidades>1</unidades>
                        </producto>
                       
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Pedro</nombre>
                    <apellidos>González Gomez</apellidos>
                    <telefono>556-122-4568</telefono>
                    <direccion>
                        <calle>Anillo Periférico</calle>
                        <ciudad>Ciudad de México</ciudad>
                        <codigo_postal>28002</codigo_postal>
                        <provincia>México</provincia>
                    </direccion>
                    <correo_electronico>pedro.gonzalez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10002</numero_pedido>
                    <fecha_compra>2021-02-03</fecha_compra>
                    <fecha_entrega>2021-02-05</fecha_entrega>
                    <total_factura>65.95</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Zapatos caballero casual planos</nombre_producto>
                            <referencia>ABC156</referencia>
                            <precio>65.95</precio>
                            <unidades>1</unidades>
                        </producto>
                       
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Paco</nombre>
                    <apellidos>Domingez Gomez</apellidos>
                    <telefono>123-122-4564</telefono>
                    <direccion>
                        <calle>Puerta del Sol.</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28003</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>paco.domingez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-06</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10003</numero_pedido>
                    <fecha_compra>2021-02-07</fecha_compra>
                    <fecha_entrega>2021-02-09</fecha_entrega>
                    <total_factura>20.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Zapato cómodo</nombre_producto>
                            <referencia>ABC178</referencia>
                            <precio>20.99</precio>
                            <unidades>1</unidades>
                        </producto>
                       
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Sergio</nombre>
                    <apellidos>Felipe García</apellidos>
                    <telefono>654-987-4564</telefono>
                    <direccion>
                        <calle>Puerta del Sol.</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28004</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>sergio.felipe@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-06</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10004</numero_pedido>
                    <fecha_compra>2021-02-10</fecha_compra>
                    <fecha_entrega>2021-02-12</fecha_entrega>
                    <total_factura>26.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>deportivas de niño</nombre_producto>
                            <referencia>ABC200</referencia>
                            <precio>26.99</precio>
                            <unidades>1</unidades>
                        </producto>
                       
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>María</nombre>
                    <apellidos>González Pérez</apellidos>
                    <telefono>555-123-4567</telefono>
                    <direccion>
                        <calle>Calle Mayor, 1</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28001</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>maria.gonzalez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-01-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10009</numero_pedido>
                    <fecha_compra>2021-01-25</fecha_compra>
                    <fecha_entrega>2021-01-27</fecha_entrega>
                    <total_factura>19.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Vestido camisero con cinturón para anudar</nombre_producto>
                            <referencia>ZSD209</referencia>
                            <precio>19.99</precio>
                            <unidades>1</unidades>
                        </producto>
                       
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Paco</nombre>
                    <apellidos>Jimenez Lopez</apellidos>
                    <telefono>677-122-4564</telefono>
                    <direccion>
                        <calle>Puerta del Sol.</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28005</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>paco.jimenez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-10</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10006</numero_pedido>
                    <fecha_compra>2021-02-11</fecha_compra>
                    <fecha_entrega>2021-02-13</fecha_entrega>
                    <total_factura>20.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>deportivo de trekking para hombre</nombre_producto>
                            <referencia>ABC180</referencia>
                            <precio>20.99</precio>
                            <unidades>1</unidades>
                        </producto>
                       
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Encarna</nombre>
                    <apellidos>Perez Delgado</apellidos>
                    <telefono>766-122-4564</telefono>
                    <direccion>
                        <calle>Calle Huertas</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28006</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>encarna.perez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-08</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10007</numero_pedido>
                    <fecha_compra>2021-02-08</fecha_compra>
                    <fecha_entrega>2021-02-10</fecha_entrega>
                    <total_factura>19.98</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Pantalón de felpa con puños en el bajo</nombre_producto>
                            <referencia>SDE321</referencia>
                            <precio>9.99</precio>
                            <unidades>2</unidades>
                        </producto>

                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Victor</nombre>
                    <apellidos>García Fernandez</apellidos>
                    <telefono>879-361-4564</telefono>
                    <direccion>
                        <calle>Puerta del Sol.</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28012</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>victor.garcia@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-10</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10028</numero_pedido>
                    <fecha_compra>2021-02-10</fecha_compra>
                    <fecha_entrega>2021-02-12</fecha_entrega>
                    <total_factura>53.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>mocasín castellano de piel</nombre_producto>
                            <referencia>OLÑ618</referencia>
                            <precio>53.99</precio>
                            <unidades>1</unidades>
                        </producto>
                       
                    </productos>
                </detalle_pedido>
            </pedido>
           <pedido>
                <cliente>
                    <nombre>Encarna</nombre>
                    <apellidos>Perez Delgado</apellidos>
                    <telefono>766-122-4564</telefono>
                    <direccion>
                        <calle>Calle Huertas</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28006</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>encarna.perez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-08</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10075</numero_pedido>
                    <fecha_compra>2021-02-26</fecha_compra>
                    <fecha_entrega>2021-02-28</fecha_entrega>
                    <total_factura>12.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Jersey tricot manga larga acabados en canalé</nombre_producto>
                            <referencia>KGQ671</referencia>
                            <precio>12.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
           
            <pedido>
                <cliente>
                    <nombre>Encarna</nombre>
                    <apellidos>Perez Delgado</apellidos>
                    <telefono>766-122-4564</telefono>
                    <direccion>
                        <calle>Calle Huertas</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28006</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>encarna.perez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-02-08</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10097</numero_pedido>
                    <fecha_compra>2021-03-03</fecha_compra>
                    <fecha_entrega>2021-03-05</fecha_entrega>
                    <total_factura>12.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Pijama camiseta manga corta </nombre_producto>
                            <referencia>GVÑ058</referencia>
                            <precio>12.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            
        </trimestre>
        <trimestre num="2">
            <pedido>
                <cliente>
                    <nombre>Natalia</nombre>
                    <apellidos>Ramirez Benito</apellidos>
                    <telefono>517-602-9148</telefono>
                    <direccion>
                        <calle>Gran Vía</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28534</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>natalia.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-04-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10098</numero_pedido>
                    <fecha_compra>2021-04-02</fecha_compra>
                    <fecha_entrega>2021-04-04</fecha_entrega>
                    <total_factura>19.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Vestido evasé punto tricot manga larga</nombre_producto>
                            <referencia>FÑC401</referencia>
                            <precio>19.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Natalia</nombre>
                    <apellidos>Ramírez Benito</apellidos>
                    <telefono>517-602-9148</telefono>
                    <direccion>
                        <calle>Gran Vía</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28534</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>natalia.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-04-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10099</numero_pedido>
                    <fecha_compra>2021-04-06</fecha_compra>
                    <fecha_entrega>2021-04-08</fecha_entrega>
                    <total_factura>80.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Chaquetón de lana liso para mujer</nombre_producto>
                            <referencia>LXZ345</referencia>
                            <precio>80.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Natalia</nombre>
                    <apellidos>Ramirez Benito</apellidos>
                    <telefono>517-602-9148</telefono>
                    <direccion>
                        <calle>Gran Vía</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28534</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>natalia.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-04-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10100</numero_pedido>
                    <fecha_compra>2021-04-10</fecha_compra>
                    <fecha_entrega>2021-04-12</fecha_entrega>
                    <total_factura>14.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Chaqueta larga de cuadros con bolsillos</nombre_producto>
                            <referencia>QGA333</referencia>
                            <precio>14.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Natalia</nombre>
                    <apellidos>Ramirez Benito</apellidos>
                    <telefono>517-602-9148</telefono>
                    <direccion>
                        <calle>Gran Vía</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28534</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>natalia.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-04-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10101</numero_pedido>
                    <fecha_compra>2021-04-13</fecha_compra>
                    <fecha_entrega>2021-04-15</fecha_entrega>
                    <total_factura>19.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Chaleco acolchado con bolsa para guardar</nombre_producto>
                            <referencia>MAW008</referencia>
                            <precio>19.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Natalia</nombre>
                    <apellidos>Ramirez Benito</apellidos>
                    <telefono>517-602-9148</telefono>
                    <direccion>
                        <calle>Gran Vía</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28534</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>natalia.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-04-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10103</numero_pedido>
                    <fecha_compra>2021-04-17</fecha_compra>
                    <fecha_entrega>2021-04-19</fecha_entrega>
                    <total_factura>15.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Falda vaquera denim elástico 5 bolsillos</nombre_producto>
                            <referencia>SÑM409</referencia>
                            <precio>15.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Carla</nombre>
                    <apellidos>Ramirez Benito</apellidos>
                    <telefono>517-602-9148</telefono>
                    <direccion>
                        <calle>Calle Huertas</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28679</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>carla.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-05-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10104</numero_pedido>
                    <fecha_compra>2021-05-02</fecha_compra>
                    <fecha_entrega>2021-05-04</fecha_entrega>
                    <total_factura>79.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Chaqueta fluida estampada</nombre_producto>
                            <referencia>JCZ100</referencia>
                            <precio>39.99</precio>
                            <unidades>2</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Patricia</nombre>
                    <apellidos>García Perez</apellidos>
                    <telefono>689-195-9148</telefono>
                    <direccion>
                        <calle>Calle Huertas</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28689</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>carla.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-05-07</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>101019</numero_pedido>
                    <fecha_compra>2021-05-07</fecha_compra>
                    <fecha_entrega>2021-05-09</fecha_entrega>
                    <total_factura>89.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Blazer de manga larga de mujer</nombre_producto>
                            <referencia>KER170</referencia>
                            <precio>44,99</precio>
                            <unidades>2</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Esperanza</nombre>
                    <apellidos>Smith Perez</apellidos>
                    <telefono>910-692-9148</telefono>
                    <direccion>
                        <calle>Wall Street </calle>
                        <ciudad>Nueva York</ciudad>
                        <codigo_postal>28779</codigo_postal>
                        <provincia>Estados Unidos</provincia>
                    </direccion>
                    <correo_electronico>esperanza.smith@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-05-26</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10174</numero_pedido>
                    <fecha_compra>2021-05-26</fecha_compra>
                    <fecha_entrega>2021-05-28</fecha_entrega>
                    <total_factura>15.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Legging sin costuras punto liso elástico</nombre_producto>
                            <referencia>TRZ050</referencia>
                            <precio>7.99</precio>
                            <unidades>2</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Sofia</nombre>
                    <apellidos>Jimenez Benito</apellidos>
                    <telefono>407-018-9148</telefono>
                    <direccion>
                        <calle>Calle Huertas</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28479</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>sofia.jimenez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-06-02</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10175</numero_pedido>
                    <fecha_compra>2021-06-02</fecha_compra>
                    <fecha_entrega>2021-06-04</fecha_entrega>
                    <total_factura>17,99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Pantalón vaquero efecto push up</nombre_producto>
                            <referencia>lCZ100</referencia>
                            <precio>17,99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Raquel</nombre>
                    <apellidos>Perez Benito</apellidos>
                    <telefono>653-783-9148</telefono>
                    <direccion>
                        <calle>Calle Huertas</calle>
                        <ciudad>Madrid</ciudad>
                        <codigo_postal>28680</codigo_postal>
                        <provincia>Madrid</provincia>
                    </direccion>
                    <correo_electronico>carla.ramirez@gmail.com</correo_electronico>
                </cliente>
                <fecha_inclusion>2021-06-27</fecha_inclusion>
                <detalle_pedido>
                    <numero_pedido>10199</numero_pedido>
                    <fecha_compra>2021-06-27</fecha_compra>
                    <fecha_entrega>2021-06-29</fecha_entrega>
                    <total_factura>15.99</total_factura>
                    <productos>
                        <producto>
                            <nombre_producto>Chaqueta cárdigan tacto mohair</nombre_producto>
                            <referencia>OYR199</referencia>
                            <precio>15.99</precio>
                            <unidades>1</unidades>
                        </producto>
                        
                    </productos>
                </detalle_pedido>
            </pedido>
        </trimestre>